spring:
  profiles:
    active: dev


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.tyy.pojo
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    com.tyy.mapper: debug

jwt:
  header: Authorization
  head: Bearer
  secret: tyyyy
  expireTime: 6048000